---
languageCode: "en-us"
title: "Roy Dammarell"
baseurl: "http://roydammarell.com/"
theme: "hugo-theme-blueberry-detox"
params:
  description: "Android Developer"
  creditBadges:
    netlify:
      src: "https://www.netlify.com/img/global/badges/netlify-light.svg"
      href: "https://www.netlify.com"
    github:
      src: "/github-logo.png"
      href: "https://github.com/royd/portfolio"
...
